name: 🟥 Bug
description: Bug report
title: '[bug]: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the issue.
    id: intro
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      value: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Provide screenshots/screencasts if relevant
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Message & Stack Trace
      description: Provide logging outputs/errors if relevant
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
        ### Developer section
        Developer section also available for any additional notes.
  - type: textarea
    id: dev-notes
    attributes:
      label: Developer Notes
      description: Any additional notes from developers. this might be consider as realease notes.
    validations:
      required: false
  - type: dropdown
    id: breaking-change
    attributes:
      label: Does this issue introduce a breaking change?
      options:
        - "Yes"
        - "No"
        - "Not Sure"
    validations:
      required: false
