name: 🟩 Feature
description: Feature request
title: '[feat]: '
labels:
  - feat
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the issue.
    id: intro
  - type: textarea
    id: steps
    attributes:
      label: Problem Statement
      description: Describe the problem you are trying to solve
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected new behavior or feature
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ### Developer section
        Developer section also available for any additional notes.
  - type: textarea
    id: dev-notes
    attributes:
      label: Developer Notes
      description: Any additional notes from developers. this might be consider as realease notes.
    validations:
      required: false
  - type: dropdown
    id: breaking-change
    attributes:
      label: Does this issue introduce a breaking change?
      options:
        - "Yes"
        - "No"
        - "Not Sure"
    validations:
      required: false
